### ISSUE TITLE
Does SAGU work with IAM and users?

### ISSUE THREAD

**Issue by coreyhahn** [brianmcmichael/SAGU#33]
it is the new year and I am doing my backups but it seems that SAGU does not work with the new IAM infrastructure?  Has anyone gotten it to work?

**Comment by coreyhahn** [comment]
java -jar ./SimpleGlacierUploaderV0747.jar 
Exception in thread "AWT-EventQueue-0" com.amazonaws.AmazonServiceException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'GET
/-/vaults
limit=1000
accept:application/json
content-type:application/x-amz-json-1.0
host:glacier.us-west-2.amazonaws.com
user-agent:aws-sdk-java/1.10.26 Linux/3.13.0-74-generic OpenJDK_64-Bit_Server_VM/24.91-b01/1.7.0_91
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20160103T184705Z
x-amz-glacier-version:2012-06-01
x-amz-target:Glacier.ListVaults

accept;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-glacier-version;x-amz-target
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20160103T184705Z
20160103/us-west-2/glacier/aws4_request
46ea1e2463eca425522edfcccdbaee8402c2eebb3144ef6f788836e6b866ff49'
 (Service: AmazonGlacier; Status Code: 403; Error Code: InvalidSignatureException; Request ID: 1FCGyEnSlYGVoqhegUZfEsWpx_b3hPsyppVBLccJenFXzMQ)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1181)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:766)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:485)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:306)
	at com.amazonaws.services.glacier.AmazonGlacierClient.invoke(AmazonGlacierClient.java:2970)
	at com.amazonaws.services.glacier.AmazonGlacierClient.listVaults(AmazonGlacierClient.java:353)
	at com.brianmcmichael.sagu.SimpleGlacierUploader.repopulateVaults(SimpleGlacierUploader.java:662)
	at com.brianmcmichael.sagu.SimpleGlacierUploader.actionPerformed(SimpleGlacierUploader.java:869)
	at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1260)
	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:588)
	at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:624)
	at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:853)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
	at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(BasicComboPopup.java:502)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by therealpecus** [comment]
I have the same issue. It also happens using the root keys

**Comment by liry** [comment]
The bug is fixed in new version. One can download it from [here](https://www.dropbox.com/s/4o98qd0irrhujos/GlacierUploader-0.75.0.jar?dl=1).

**Comment by coreyhahn** [comment]
cah@obiwan:~/backupcopy$ java -jar GlacierUploader-0.75.0.jar 
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/brianmcmichael/sagu/SAGU : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

Can you compile targeting version 1.7 (version 7) of the JRE as I am running LTS Ubuntu 14.04?

Thanks a bunch

**Comment by liry** [comment]
@coreyhahn here's fixed build of previous version you can use with older java: [GlacierUploader-0.74.7.jar](https://www.dropbox.com/s/qxe98uqwkbhx89s/GlacierUploader-0.74.7.jar?dl=0).
New version does depend on Java 8 or newer (Java 7 End of Life was in April 2015).
